### ISSUE TITLE
[Tarea 2] Clarificacion 2-lookahead

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#10]
Existe un limite sobre la cantidad de veces que se puede realizar el lookahead de manera consecutiva? Por ejemplo si estoy en el estado P4, y veo la primera letra que viene en la palabra, veo que es una "a" y me muevo al estado P5. Esta "a" no ha sido consumida todavía, entonces mi pregunta es, puedo de nuevo ver una letra hacia adelante, que seria la misma "a", y avanzar a un estado P6, sin consumir la "a"?

**Comment by fdoflorenzano** [comment]
Hola,
El enunciado no establece ninguna restricción sobre eso. No debería haber un límite en cuantas de esas transiciones se pueden realizar. Como dices, cada vez que se hace una, no se avanza en la palabra. Eso da espacio para seguir más de una de esas transiciones de manera consecutiva.
