### ISSUE TITLE
Expresiones Regulares

### ISSUE THREAD

**Issue by Jaluco** [PUC-IIC2223/syllabus2018#11]
Existe alguna guía para saber bien que hace cada símbolo en regex? En internet hay varias versiones diferentes y me gustaría tener acceso a alguna más acorde a lo visto en clases (ya que las diapositivas simplemente muestran los distintos símbolos)

**Comment by fdoflorenzano** [comment]
Hola,
Como bien dices, en internet encontrarás varios estándares de _syntaxis_  para expresiones regulares, como: POSIX y Perl ([fuente](https://en.wikipedia.org/wiki/Regular_expression#Syntax)). Ojo, que estas se refieren a expresiones regulares **en la práctica**, es decir, para sistemas que implementan su evaluación. Estos estándares se diferencian bastante del modelo visto en clase, tanto en operadores, _syntaxis_, y poder expresivo. Si tu pregunta es para aprender para el curso, te recomiendo que te mantengas con la referencia vista en clases y su semántica, ya que puede que te confundas si estudias viendo el lenguaje de la práctica. En su defecto, deberías buscar por referencias de teoría, como libros de autómatas. Puedes buscar en la bibliografía del curso varios libros.

**Comment by Jaluco** [comment]
Ok gracias, preguntaba para aprender del curso, las expresiones vistas en clases no me ayudan porque en las diapositivas no estan explicadas y como mal estudiante que soy no vi necesario tomar apuntes al respecto. Ahora parto revisando la bibliografía.
