### ISSUE TITLE
[Lab1] Aclaración Input

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#12]
2 dudas:

- Primero, ¿podemos asumir que el path que se ingresa al correr el .py lleva a un archivo valido? En la misma linea, podemos asumir que cada linea en el archivo tendra el formato correcto?

- Segundo, ¿podemos asumir que los nombre de los estados serán siempre números naturales? Esto dado que tenemos que completar las transiciones, necesitamos un estado sumidero, al cual quiero darle un nombre estándar, sin preocuparme que sea el mismo nombre que algún estado del input.

**Comment by crivero1** [comment]
Sobre la primera pregunta, si puedes asumir que el path que se ingresa lleva un archivo válido (no lo probaremos con archivos inválidos). Ahora bien, entre más "robusto" tu programa mejor. Así te aseguras que no se caerá por alguna tontera al probarlo. 

Sobre la segunda pregunta, también puedes asumir que serán números naturales (así serán nuestros ejemplos de prueba). De todas formas coloca esta suposición en el README de tu solución. 

Saludos y suerte!

**Comment by benjavides** [comment]
Podemos asumir que los nombres de los estados siempre partirán desde el 0 y serán todos continuados? Con continuados me refiero a que los estados pueden ser 0,1,2,3,4 y no 0,1,2,4,5

**Comment by crivero1** [comment]
Hola Benjamín, 

No puedes asumir esto. Si bien se usarán números para representar estados, prefiero que no asumas que estarán continuos ni que tienen un orden predefinido. Entre menos cosas asumas del input (que no están mencionadas en el enunciado), mejor. 

Suerte!
