### ISSUE TITLE
[Lab 1] Librerías permitidas

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#13]
Abro esta issue para concentrar dudas de librerías permitidas para el laboratorio 1 😀 y de pasada preguntar si se puede usar `collections` para hacer uso de `defaultdict`.
Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Estimado,
Si está permitido el uso de `defaultdict` de `collections`.

PD: Gracias por crear esta _issue_. Cualquier duda de librería por favor comentarla aquí.

**Comment by llloyola** [comment]
Hola! Puedo usar la librería ```itertools``` para importar ```product``` y hacer un producto cartesiano entre los estados del autómata? 😄

**Comment by fdoflorenzano** [comment]
@llloyola ¡Hola! Sí, está permitido el uso de `product` de `itertools`.

**Comment by llloyola** [comment]
Hola! Puedo usar ```combinations_with_replacement```de ```itertools```? 😄

**Comment by fdoflorenzano** [comment]
@llloyola ¡Hola! Sí, se puede usar `combinations_with_replacement` de `itertools`.
