### ISSUE TITLE
[Lab1] Tests

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#14]
Quería saber si existe la posibilidad que suban tests para probar nuestro código.

**Comment by fdoflorenzano** [comment]
Hola,
Subiremos tests de ejemplo entre el jueves y el viernes de esta semana.
Saludos.

**Comment by fdoflorenzano** [comment]
Hola de nuevo,
Se subieron al Siding un conjunto de archivos de ejemplos de _inputs_ posibles para el laboratorio.
Saludos.
