### ISSUE TITLE
compilar

### ISSUE THREAD

**Issue by sameneses** [PUC-IIC2223/syllabus2018#15]
Hola

Me llama la atención que el enunciado diga que hay que dar instrucciones sobre como compilar el código.
No tengo experiencia compilando python, pero según lo que yo entiendo, compilar tendría que ser algo estándar para cualquier archivo, por no mencionar que, dado que python es un lenguaje interpretado, no es necesario compilar para ejecutar un programa.
Pregunto porque tengo la impresión de que hay algo que no estoy entendiendo, no por querer contradecir las instrucciones.

Muchas gracias

**Comment by fdoflorenzano** [comment]
Hola,
Es un _decir_, se refiere a dar instrucciones para hacer funcionar tu programa. No es necesario generar un ejecutable. Basta con un programa de extensión `.py`.

Saludos.

**Comment by crivero1** [comment]
Hola Sebastián,

Si tu compilación solo llama el compilador y tu código, bueno explica solo eso. Si necesitas hacer algo más complicado, para eso esta el README. Estas entendiendo todo bien. 

Suerte!

**Comment by sameneses** [comment]
Gracias
