### ISSUE TITLE
Sumideros en lab1

### ISSUE THREAD

**Issue by seba-bug** [PUC-IIC2223/syllabus2018#16]
Hola!

Cuando tenemos que completar un autómata determinista con función parcial de transición, se espera que llamemos al estado sumidero con el primer natural no usado en el autómata que nos dan o da lo mismo cómo lo llame?

Gracias!

**Comment by crivero1** [comment]
Hola Sebastian, 

Como tu quieras llamarlo. Ustedes deciden como solucionarlo.

Suerte!
