### ISSUE TITLE
Transiciones repetidas lab1

### ISSUE THREAD

**Issue by seba-bug** [PUC-IIC2223/syllabus2018#17]
Hola!

El test 3 del laboratorio 1 tiene una transición repetida, en particular, del estado 3 al 6 consumiendo una b-letra. Mi duda es si eso vuelve al autómata en no-determinista. Según lo que me imaginaba, como sigue siendo la misma transición no vale como dos opciones para ir desde 3 -> 6. No me cabe duda que sí sería NFA si existieran dos transiciones desde 3 con la misma letra y que llegan a estados distintos.

Gracias

**Comment by fdoflorenzano** [comment]
Hola Seba,
Gracias por la observación. Fue un caso que se nos pasó, dos transiciones repetidas no debiesen aparecer en el input. Como dices, debiese aún considerarse determinista, pero fue un error de ejemplo que se nos pasó a nosotros. Corregí ese test en el Siding.
Saludos.
