### ISSUE TITLE
[lab1] Eliminación de estados innecesarios

### ISSUE THREAD

**Issue by seba-bug** [PUC-IIC2223/syllabus2018#18]
Hola!

Asumí que teníamos que eliminar los estados innecesarios (aquellos sin entradas desde otro estado o que no son estados iniciales), a pesar de que en el algoritmo de minimización no sale explícito. ¿Se espera que los descartemos?

Gracias!

**Comment by frvalenzuela** [comment]
Yo tenía la misma duda. Pero luego me di cuenta que el algoritmo de la clase en la diapositiva 29 de la clase de minimazación es para colapsar estados equivalentes (que es la segunda parte del algoritmo completo). El verdadero algoritmo de minimización está en las diapositivas 2, 3 y 4. Así que deberías estar bien!

**Comment by crivero1** [comment]
Hola Sebastián,

Si, tu algoritmo debe considerar eliminar estados inalcanzables. Esto lo puedes hacer antes de encontrar los estados equivalentes, o después de hacer el autómata cuociente. 

Saludos!

**Comment by benjavides** [comment]
(Duda de la tarea relacionada con esto)
Si tenemos un autómata que ya está minimizado, podemos asumir que no tiene estados inalcanzables? Por qué?

**Comment by crivero1** [comment]
Hola Benjamín,

Si con "minimizado" te refieres a que el autómata paso por el algoritmo de minimización, entonces la respuesta es si, no tiene estados inalcanzables dado que el algoritmo cuenta con que tu removiste primero los estados inalcanzables. Al hacer después el autómata cuociente, cada clase tiene por lo menos un estado alcanzable, así que todos los estados son alcanzables. 

Si con "minimizado" te refieres al autómata mínimo equivalente, entonces no puede tener estados inalcanzables, dado que entonces no sería mínimo (si le elimino ese estado inalcanzable encuentro un autómata que tiene menos estados y es equivalente). 

En ambos casos la respuesta es si :)

Suerte!
