### ISSUE TITLE
Herramienta para dibujar autómatas en LaTex

### ISSUE THREAD

**Issue by fdoflorenzano** [PUC-IIC2223/syllabus2018#2]
Pueden utilizar esta [página](http://madebyevan.com/fsm/).

**Comment by fgbruna** [comment]
No habrá alguna forma de usar curvas para las transiciones sin meterle mano al código en `tikz` ?

**Comment by crivero1** [comment]
Hola Franco,

Al parecer no se puede en la interfaz. Ahora bien, en el código que te genera la aplicación que dio Fernando, el código latex debe contener algo como:

\draw [black] (21.79,-25.69) -- (50.71,-23.71);

Esto es lo que genera una transición entre dos puntos. Para hacer que se dobla, cambialo por lo siguiente:

\draw [black] (21.79,-25.69) edge[bend left] (50.71,-23.71);

Saludos!

**Comment by SHGoldfarb** [comment]
Se pueden hacer flechas curvas arrastrando una flecha existente.

**Comment by fgbruna** [comment]
@SHGoldfarb solo clickeando la flecha y arrastrando ?, juro que lo he intentado de miles de formas y no me funciona 😕, al final lo hice a mano en tikz, pero me parece raro que no se pueda hacer en la página

**Comment by frvalenzuela** [comment]
@fgbruna también tienes que apretar la tecla shift

**Comment by AlfonsoIgnacioV** [comment]
También encontré esta otra [página](http://www.texample.net/tikz/examples/state-machine/), es bastante intuitiva la forma en que se construye, y se ve ordenado.
