### ISSUE TITLE
[Laboratorio 1] Path del output

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#20]
Dónde se debe crear el archivo `automata-min.txt`?
a) Junto a `minimizador.py`
b) Junto a `automata.txt`
(Estos archivos podrían no estar en la misma ubicación)

**Comment by fdoflorenzano** [comment]
Debido a que el enunciado no especifica, puede crearlo donde creas más natural. Recuerda especificar en tu `README` cómo lo asumiste, para que le corrector no se sorprenda.
