### ISSUE TITLE
[Lab 1] Deducción alfabeto de entrada.

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#22]
En el enunciado del laboratorio 1 se dice lo siguiente:
> Note que no es necesario declarar el conjunto de estados o alfabeto de entrada, ya que este se puede deducir desde las mismas líneas de transiciones.

Pero no me queda claro cómo deberíamos hacer esta deducción.
Por ejemplo, podemos asumir que el alfabeto está compuesto por las letras que tienen ***al menos una transición*** asociada en el autómata original?, es decir si tomamos el siguiente autómata dado por el archivo de ejemplo 4:
```
t 0 a 1
t 1 a 2
t 2 a 3
t 3 a 4
t 4 a 5
t 5 a 0
i 0
f 1
f 4
```
Este no presenta nada más que a-letras en sus transiciones por lo que es razonable asumir que el alfabeto es {a} ?
Digo esto por que creo que podria prestarse para confusiones al momento de determinizar  y por lo tanto el autómata mínimo podría ser distinto al esperado.
Gracias de antemano!

**Comment by benjavides** [comment]
Yo entendí que es como dices. El alfabeto está compuesto por todas las letras que fueron usadas en al menos una transición.

**Comment by fdoflorenzano** [comment]
Sí, a eso se refiere.
