### ISSUE TITLE
[Tarea 3] 1.2 Caso borde

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#23]
En la pregunta 1.2
![image](https://user-images.githubusercontent.com/7333792/46372602-0521dc80-c662-11e8-90b4-29d62abf6466.png)
Consideramos que el n es distinto de cero?
Si n puede tomar el valor cero y 
![image](https://user-images.githubusercontent.com/7333792/46372790-7eb9ca80-c662-11e8-9c28-1e866fd7a75e.png)
entonces cuando epsilon pertenece a L, cualquier cosa pertenece al lenguaje que queremos definir.

**Comment by AlfonsoIgnacioV** [comment]
Hola @benjavides , yo imagino que _n_ no puede tomar el valor 0, ya que 0 no pertenece a los naturales.
Saludos!

**Comment by crivero1** [comment]
Hola Benjamín,

Según la definición, n puede tomar el valor 0 (ojo: el 0 siempre esta en los naturales según la definición conjuntista de los naturales) y por lo tanto si el \epsilon esta en L, L^{\exists n} es igual a todas las palabras. Este es un caso borde. Si complica mucho tu solución, puedes colocar en tu respuesta que supones que n > 0 y hacer todo según esa suposición, no hay problema.

Saludos!
