### ISSUE TITLE
Material de estudio Clases 11, 12, 13

### ISSUE THREAD

**Issue by caespinoza5** [PUC-IIC2223/syllabus2018#24]
Dado que el contenido que se está viendo en estas clases está siendo dictado por primera vez, ¿Qué material de estudio recomiendan para profundizar teoría y/o ejercitar para la I2?

¡Gracias de antemano!

**Comment by crivero1** [comment]
Hola,

Acabo de enviar un anuncio en SidIng de donde encontrar material de estudio para la materia nueva. Sobre ejercicios, podrán sacar ejercicios de la Tarea 3 y Tarea 4, y de las ayudantias. Trataremos de publicar una guía con ejercicios antes de la I2 con ejercicios de la materia nueva.

Saludos!
