### ISSUE TITLE
[Tarea 3] Pregunta 2.2

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#26]
Qué spans debería ser capaz de encontrar nuestro algoritmo en un caso como este?
![image](https://user-images.githubusercontent.com/7333792/46507596-b3b75000-c80f-11e8-94fc-a9350ad5c7bd.png)

**Comment by frvalenzuela** [comment]
Puedo estar equivocado, pero según como yo lo entiendo, debería ser capaz de encontrar el [1, 7[ y el [16,23[

**Comment by crivero1** [comment]
Hola Benjamín,

Si, el resultado de la semántica es el [1, 7[ y [16,23[ como dice Felipe.

Suerte!
