### ISSUE TITLE
Uso de github

### ISSUE THREAD

**Issue by Jaluco** [PUC-IIC2223/syllabus2018#27]
¿Por qué no usamos el repositorio de github para subir enunciados y clases?
Asi sería mucho más sensillo contar con los materiales del curso, ¿o no?

**Comment by crivero1** [comment]
Hola José Antonio, 

Si, no es mala idea. Esta es primera vez que uso github como foro en un curso. Para no meter ruido, nos mantendremos como estamos. Lo más seguro es que las futuras versiones del curso sean solo en github.

Saludos!
