### ISSUE TITLE
función updateSet

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#28]
Creo que no me termina de quedar claro cuál es el objetivo de esta función en el algoritmo de leftmost-longest, se que el pseudocódigo está en las slides, pero si alguien pudiera explicar a grandes rasgos su función  en el algoritmo le estaria agradecido.
Gracias de antemano!

**Comment by crivero1** [comment]
Hola Franco,

El objetivo de la función es actualizar el conjunto de pares (estado, inicio) según la relación de transición y letra actual.  Lo que hace es que para cada par (p,k) en el conjunto actual y para cada transición de la forma (p, a_i, q), agrega/actualiza el estado q según el valor k. Si el estado q es primera vez que se agrega al nuevo conjunto P_t (el "elseif") entonces se agrega (q, k), lo cual representa una ejecución que partió en la posición k. En cambio, si ya existía un par (q, k') en P_t y ese k' es mayor que el k, entonces quiere decir que el (p, k) representa una ejecución que partió mas a la izquierda (leftmost), y por lo tanto queremos recordarla sobre el k'. Entonces removemos el (q,k') de P_t y agregamos el (q,k) al nuevo conjunto. 

¿Se entiende? Si todavía no queda muy claro, por favor, acércate después de clases o anda a mi oficina y te lo explico mejor.

Suerte!
