### ISSUE TITLE
Palabra vacía

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#3]
En la pregunta 1.1 
![image](https://user-images.githubusercontent.com/7333792/44688805-c62db500-aa2b-11e8-81d8-55077e770850.png)

**La palabra vacía cumple ambas propiedades o no?**
Se me ocurren 2 formas de verlo:
1. No hay posiciones en la palabra vacía por lo tanto las condiciones se cumplen trivialmente.
2. Se cumple la condición par porque hay 0 a's en posiciones pares. No se cumple la condición impar porque hay 0 a's en posiciones impares.

**Comment by crivero1** [comment]
Hola Benjamín,

La verdad que este es un caso borde y creo que ambas formas de verlo es válida. Ahora bien, si  vemos la definición del lenguaje como un "para toda posición par ... y para toda posición impar ... " ambos "para todos" se hacen trivialmente verdaderos en el caso de la palabra epsilon  y, por lo tanto, la palabra epsilon debe estar en el lenguaje. 

Suerte!

**Comment by fgvenegas** [comment]
Y para el caso de la palabra "b", se debería analizar como la segunda forma que menciona Benjamin?

**Comment by crivero1** [comment]
Freddy y Benjamin,

Después del comentario de Freddy me di cuenta que estaba totalmente equivocado. Para el caso borde en que no hay posiciones pares o impares, es razonable suponer que el número de letras 'a's es 0. Por lo tanto, la palabra '\epsilon' no esta en el lenguaje, al igual que no esta la palabra 'b'. 

El razonamiento que di en mi respuesta anterior no tiene sentido, ya que la especificación no pasa por un tema de cuantificación lógica, si no que por un tema de conteo. 

Suerte!

**Comment by fgvenegas** [comment]
Vale gracias!
