### ISSUE TITLE
[Lab 2] tests

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#30]
Hola, se que es un poco pronto, pero existe la posibilidad de que suban archivos para testear nuestro código?

**Comment by fdoflorenzano** [comment]
Hola, se subirán dentro de los próximos días unos ejemplos de input. Saludos.

**Comment by fdoflorenzano** [comment]
Hola, se subieron algunos ejemplos para el laboratorio. Saludos.
