### ISSUE TITLE
[Lab 2] Saltos de línea 

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#31]
El `autómata.txt` tendrá definidos los caracteres de salto de línea (`\n` y `\r`) en su vocabulario o al leer el `documento.txt` borro estos caracteres?

**Comment by crivero1** [comment]
Hola Benjamín,

El autómata se ejecutará sobre todo el documento. Por lo tanto \n o \r también serán un posible símbolo del vocabulario del autómata y no debes removerlos. 

Suerte!

**Comment by Mdelaf** [comment]
Hola,

¿Esto significa que en el archivo del autómata podríamos recibir transiciones como lo siguiente?
```
t 0 \n 1
t 0 \r 1
```

**Comment by crivero1** [comment]
Hola,

Si, puedes recibir ese tipo de transiciones. Ahora bien, para simplificar el manejo de estos casos bordes no probaremos ejemplos con es tipo de transiciones. Así que si tu solución no las soporta, no importa.

Saludos!

**Comment by gafigueroa** [comment]
Hola,

¿Se puede recibir espacio como un carácter posible?

Por ejemplo una transición del estilo

```
t 0   1
```

**Comment by crivero1** [comment]
Hola Guillermo,

En general, deben soportar por lo menos símbolos del abecedario, en mayúsculas y minúsculas, junto con dígitos del 0 al 9. Todos los ejemplos que probaremos serán patrones simples sobre ese conjunto de símbolos. Si puedes soportar más símbolos, mejor, pero no serán usados en la evaluación.

Saludos!
