### ISSUE TITLE
Enunciado Laboratorio - span (3, 8)

### ISSUE THREAD

**Issue by caespinoza5** [PUC-IIC2223/syllabus2018#32]
Una duda:

Según mi programa, el primer span que se debiese entregar sería (3, 7), no (3, 8) (dado la palabra w y el autómata automata-NFA), porque la palabra "baaab" no es aceptada por el autómata, cierto?

**Comment by fgbruna** [comment]
Lo mismo, si seguimos la definición de clases:
![image](https://user-images.githubusercontent.com/26395700/47191221-66ada080-d31c-11e8-97ff-774c48e554d3.png)
deberia ser [3, 7)

**Comment by crivero1** [comment]
Cristobal y Franco,

Gracias por su comentario. Es verdad, el enunciado esta equivocado: el primer output debería ser [3, 7) y no [3, 8), ya que el autómata llega a un estado final cuando mira la última "a" y no la "b" (en un principio había colocado el estado 1 también como final, pero después lo removí y no me di cuenta que cambiaba el output). 

Suerte!
