### ISSUE TITLE
Recorreccion

### ISSUE THREAD

**Issue by sameneses** [PUC-IIC2223/syllabus2018#33]
Hola
¿Podrían subir los autómatas del lab 1 para ver en que nos equivocamos?
Esta la posibilidad de recorregir, pero no tengo idea de que es lo que hice mal.

**Comment by fdoflorenzano** [comment]
Estimado, se publicó un aviso sobre este tema. Saludos.

**Comment by sameneses** [comment]
muchas gracias

**Comment by sameneses** [comment]
El cuestionario de recorreccion esta cerrado
Se supone que tendria que estar abierto hasta el 29

**Comment by fdoflorenzano** [comment]
Gracias por avisar, hubo una confusión al crear el cuestionario, ahora sí.
