### ISSUE TITLE
[Lab 2] Capacidad de partir de estado inicial

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#34]
Al ejecutar `NFA01.txt` de los ejemplos subidos
![image](https://user-images.githubusercontent.com/7333792/47321600-a67dcc00-d62b-11e8-8122-c8c8b99e08dc.png)
con **w= abaaab**.

Siguiendo el [pseudocódigo visto en clases](https://i.snag.gy/wQgSs2.jpg), pero partiendo de i=0.
La ejecución puede verse asi:

>###i=0### leyendo letra: a
No hay candidato (s=null) asi que agregamos estados iniciales.
P: [[0, 0]]
P1: [[0, 0]]

>###i=1### leyendo letra: b
No hay candidato (s=null) asi que agregamos estados iniciales.
P: [[0, 0], [0, 1]]
P1: [[1, 0]]
Candidato nuevo encontrado! (ab) **<-- No se hace output porque hay elementos en P1**

>###i=2### leyendo letra: a
P: [[1, 0]] **<-- No agregamos estados iniciales porque hay un candidato (ab)**
P1: []
Output span: (0,2)
**Output palabra: ab** 

>###i=3### leyendo letra: a
No hay candidato (s=null) asi que agregamos estados iniciales.
P: [[0, 3]]
P1: [[0, 3]]

>###i=4### leyendo letra: b
No hay candidato (s=null) asi que agregamos estados iniciales.
P: [[0, 3], [0, 4]]
P1: [[1, 3]]
Candidato nuevo encontrado! (ab)

>###i=5### leyendo letra: a
P: [[1, 3]]
P1: []
Output span: (3,5)
**Output palabra: ab** 

Lo correcto no sería que el último output sea **aab**? Para eso el autómata tendría que haber tenido la posibilidad de partir desde el estado inicial cuando i=2. El autómata no debería ser siempre capaz de poder partir desde el principio?

**Comment by afquintana95** [comment]
Asumo que querias decir **w=abaaba**.

> ###i=2### leyendo letra: a
P: [[1, 0]] <-- No agregamos estados iniciales porque hay un candidato (ab)
P1: []
Output span: (0,2)
Output palabra: ab

En este paso debes resetear el _i_ a s.end (la siguiente iteracion parte con _i_ = s.end) despues de hacer output, por lo tanto volverias a _i_ = 2 y entonces agregarias [[0, 2]] en tu conjunto P, cumpliendose lo que planteas al final.

**Comment by benjavides** [comment]
@afquintana95 Tienes razón, el **w** era el que indicas. Y mi error es que estaba seteando el i = s.end, pero justo después venía i+=1 y por eso se saltaba la letra. Muchas gracias!
