### ISSUE TITLE
[Lab 2] Estados iniciales y finales

### ISSUE THREAD

**Issue by AntoniaMendoza** [PUC-IIC2223/syllabus2018#35]
Hola, me queda una duda respecto del enunciado.

En una parte dice lo siguiente:

> Noté que, a diferencia del algoritmo de evaluación _evalLeftmostLongest_ visto en clase, su evaluación debe considerar también múltiples estados iniciales, como también estados iniciales que pueden ser finales, lo cual puede producir spans “vacı́os” como outputs.

Respecto a esto, ¿qué esperan que hagamos, que incluyamos los spans vacíos o que no los incluyamos? No me queda claro con el enunciado. Además, ¿esperan que modifiquemos el autómata para que deje un único estado inicial o modificamos el algoritmo para correr con varios estados iniciales?

Gracias,
Antonia

**Comment by crivero1** [comment]
Hola Antonia,

Como bien dice el enunciado, el autómata del input puede contener múltiples estados iniciales como también los estados iniciales pueden ser finales, por lo que el span vació puede ser un posible output. La verdad que no "esperamos" ninguna solución en particular. Tu te debes encargar de ver como modificar el algoritmo visto en clases para que soporte este tipo de extensiones. Eres libre de hacerlo como quieras. 

Espero responder tu pregunta. 

Suerte!
