### ISSUE TITLE
[Lab 2] Spans vacíos

### ISSUE THREAD

**Issue by caespinoza5** [PUC-IIC2223/syllabus2018#36]
¿Para todos los documentos que acepten el span vacío, el intervalo final del documento es aceptado?
Por ejemplo, si tenemos el siguiente autómata:

```
i 0
t 0 a 1
f 0
f 1

```

y la palabra "a", Entonces debiese entregar como output los spans [1, 2) y [2, 2),  no? (ya que el "i" parte desde span1.end, que sería 2).

**Comment by crivero1** [comment]
Hola,

Dada la semántica de Leftmost-longest que vimos en clases, si, siempre se debería entregar este span si el autómata acepta el span vacío (estado inicial es al mismo tiempo final). Ahora bien, para tu solución si encuentras este caso extremo esta bien. Si no, no te preocupes que no lo consideraremos durante la corrección: cuando probemos el caso borde en que el autómata acepta span vacío, consideraremos ambas soluciones como correctas (el entregar el último span como no entregarlo).

Suerte!

**Comment by caespinoza5** [comment]
¡Muchas gracias!

**Comment by SHGoldfarb** [comment]
Hola, tengo una duda similar: Si considreamos el mismo autómata anterior con la palabra "b", según la semántica de Leftmost-Longest que está en las slides (corríjanme si me equivoco), el primer span sería [1,1) y el siguiente [1,1), y así infinitamente. A esto se me ocurren dos soluciones:

1) Ignorar los spans vacíos.
2) Aceptar una sola vez cada span (en este caso quedarían los spans [1,1) y [2,2) en el output)

¿Cuál solución se espera que implementemos?

**Comment by pdpino** [comment]
Sólo viendo esto:
![image](https://user-images.githubusercontent.com/20805451/47515302-e249a900-d858-11e8-84b7-a9731622e723.png)
Yo también entiendo que si el span k-ésimo es vacío, entonces k+1, k+2, ... y todos los siguientes son el mismo span vacío.

Sin embargo, viendo esto de una slide anterior:
![image](https://user-images.githubusercontent.com/20805451/47515414-3b194180-d859-11e8-9364-2bb6e2341bd6.png)
Habría que ignorar los spans vacíos

**Comment by fgvenegas** [comment]
En el caso del autómata:
```
i 0 
f 0
```
y el documento: **abbbbccbcaaac** (uno cualquier en verdad)
¿Qué se esperaría como output?

**Comment by crivero1** [comment]
Gracias Samuel, Pablo y Freddie por la pregunta. En la definición vista en clases, claramente hay un problema cuando hay spans vacíos como [i,i), ya que cuando la semántica Leftmost-longest encuentra un span vacío, se queda "pegado" en ese span vacío y no avanza más. Ahora bien, es fácil modificar la semántica de Leftmost-longest para que tenga sentido y siga avanzando cuando hay un span vacío. Por ejemplo, uno puede extender la definición de la siguiente manera:

s_k = \min { [R] - ({s \in Span(w) | s.start < s_{k-1}.end} \cup {s_{k-1}} ) }

En otras palabras, cada vez que se toma el mínimo, se saca también el span de la solución anterior (esto es, el s_{k-1}). Obviamente, siempre queremos seguir evaluando en la posición siguiente y no quedarnos pegado en el mismo resultado. Para que no haya confusión, quédense con esta semántica. No debería cambiar mucho la solución que tienen hasta ahora.

En el ejemplo degenerado preguntado por Freddie, el autómata entregaría como output todos los spans de la forma [i, i). 

Suerte!
