### ISSUE TITLE
[Lab 1] Duda recorrección

### ISSUE THREAD

**Issue by seba-bug** [PUC-IIC2223/syllabus2018#37]
Hola Automatines

¿La recorrección del lab 1 es arreglar el código para pasar los test fallidos? ¿En qué consiste exactamente?

Gracias!

**Comment by afquintana95** [comment]
Hola Seba!

La idea de la recorreccion era ver si algun test salio mal por un error de como se hicieron los tests (por ejemplo "mi programa asumia que los nombres de estados eran letras y no numeros") o por si marcamos como malo un test que pasaba correctamente.

Modificaciones de codigo seran aceptadas solo si fue un error absolutamente menor (por ejemplo que faltaba una coma en la linea 42).

**Comment by seba-bug** [comment]
Perfecto, muchas gracias 😃
