### ISSUE TITLE
Pregunta 1

### ISSUE THREAD

**Issue by fgvenegas** [PUC-IIC2223/syllabus2018#4]
Para la pregunta 1.1,
¿Basta con dibujar el automáta o es necesario también dar la definición formal de éste?

Gracias.

**Comment by crivero1** [comment]
Hola Freddie,

Si, para este tipo de pregunta basta con dibujar al autómata. Si no lo quieres dibujar, también puedes dar la tabla de transiciones. 

Saludos!

**Comment by pdpino** [comment]
Me cuelgo del issue para preguntar:
¿Es necesario demostrar la 1.1 y 1.2? Demostrar que el autómata y la expresión regular efectivamente definen lo que se pide

**Comment by fdoflorenzano** [comment]
Hola, no es necesario demostrarlo formalmente. Basta con expresar el autómata y expresión. 
De todas formas, recomiendo agregar algún tipo de explicación breve de tu respuesta para la corrección.

Saludos.

**Comment by crivero1** [comment]
Solo para complementar la respuesta de Fernando, se les recomienda colocar una explicación del autómata o expresión regular para facilitar la corrección del ayudante.
