### ISSUE TITLE
[Administrativo] Notas Tareas 

### ISSUE THREAD

**Issue by fgvenegas** [PUC-IIC2223/syllabus2018#40]
Hola!

Debido a que en la tarea 3 quedo una pregunta opcional, como se realizará el calculo de las notas de las tareas con este cambio? 

De antemano gracias 🍐 
Freddie

**Comment by fdoflorenzano** [comment]
Hola Freddie,

Gracias por la pregunta. Originalmente, en total habían 12 notas de tareas, de las cuales se consideraban las mejores 9 para promediar y dar la nota de tareas.

Pero luego, la T3P2 quedó como opcional para reemplazar otra nota. Entonces ahora hay un total de 11 notas a considerar (todas menos la T3P2), se consideran las mejores 8 de esas, y de ese conjunto, la nota de T3P2 puede reemplazar la peor si beneficia.

Espero haya quedado claro 🍋 
Fernando.

**Comment by fgvenegas** [comment]
Si está claro, muchas gracias!

**Comment by fdoflorenzano** [comment]
Ahora, del total de 11 preguntas obligatorias, se considerarán las 8 mejores notas, y de esas, se reemplazará la T3P2 y/o la T7P1 por las peores, si beneficia.
