### ISSUE TITLE
[Tarea 5 P2] Complemento de L

### ISSUE THREAD

**Issue by caespinoza5** [PUC-IIC2223/syllabus2018#41]
¿El complemento de L incluye todas las palabras que no son de la forma a^i b^j c^k?

Por ejemplo, ¿el complemento de L contendría la palabra "ba"?

**Comment by crivero1** [comment]
Hola Cristobal,

Si, incluye las palabras que no son de la forma a*b*c* como, por ejemplo, la palabra "ba". 

Suerte!

**Comment by caespinoza5** [comment]
¡Gracias!
