### ISSUE TITLE
[Tarea 5 P2] Posiciones Distinguidas

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#42]
No entiendo los que significa "para todo marcado de N o mas posiciones de z como 'distinguidas' ". A que se refiere con marcado de N y distinguidas?

**Comment by crivero1** [comment]
Hola,

Significa que tu puedes marcar la palabra en N posiciones distintas. Por ejemplo, si la palabra es aaaee, entonces un posible marcado de N=2 posiciones podría ser aáaeé donde los acentos son las posiciones marcadas. ¿Se entiende?

Saludos!

**Comment by rudyjb24** [comment]
Si, muchas gracias.

**Comment by sameneses** [comment]
¿Puede ser cualquier posición? ¿no hay que definir alguna clase de regla ni nada?
No entiendo cual es el sentido de las posiciones distinguidas

**Comment by crivero1** [comment]
Cualquier posición. Notar que al hacer el contrapositivo del Lema, ustedes serán los que eligen la palabra y el marcado, por lo que les da  más facilidades para demostrar que un lenguaje no es libre de contexto.

Suerte!

**Comment by sameneses** [comment]
Gracias

**Comment by sameneses** [comment]
Otra cosa
Hice las demostraciones, pero no menciono lo de los marcados.
¿es eso un problema?

**Comment by crivero1** [comment]
Hola Sebastián,

Perdona la respuesta tardía, acabo de ver que se me paso esta pregunta.

No importa que no hayas usado el Lema de Ogden. Este lema era una forma de que conocieran y revisarán el lema de bombeo para CFG y una ayuda para hacer la demostración. Si no lo tuviste que utilizar, no hay problema. 

Saludos!
