### ISSUE TITLE
[Tarea 6] Criterio de aceptación

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [PUC-IIC2223/syllabus2018#43]
Hola! Tengo la siguiente duda: en el caso de que un autómata apilador acepte algo, 
1. En la pregunta 1, ¿la idea es que el que construyamos lo acepte por stack vacío, por estado final, o da lo mismo? 
2. En la pregunta 2, ¿El que ya existe y que hay que modificar, acepta por stack vacío, por estado final, o da lo mismo?

Gracias! Saludos

**Comment by crivero1** [comment]
Hola Alfonso,

En ambos casos da lo mismo. En 1) puedes construir un autómata con stack vacío o por estado final y en 2), también puedes asumir cualquier de los dos casos. Como se demostró en clases, ambos criterios de aceptación definen el mismo conjunto de lenguajes y, por lo tanto, ambos son equivalentes en términos de lo que pueden computar. 

Suerte!

**Comment by AlfonsoIgnacioV** [comment]
Gracias!
