### ISSUE TITLE
Definición DPDA

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#44]
No me quedan claros los valores posibles para los elementos del alfabeto del stack en la siguiente definición:
<img width="893" alt="captura de pantalla 2018-11-07 a la s 19 12 36" src="https://user-images.githubusercontent.com/26395700/48164577-ac2d1000-e2c1-11e8-8b58-d08b871fdbc3.png">
Esta A es fija o es para toda A?
Por ejemplo, si tengo un estado p para el cual están definidas solo las siguientes transiciones:

- viendo cierto tope del stack y leyendo cierta letra...
- viendo otro tope del stack y leyendo otra letra...
- viendo otro tope distinto, leyendo epsilon...

Estaría cumpliendo con la definición que vimos en clases?
Saludos y gracias de antemano!

**Comment by crivero1** [comment]
Hola Franco,

Gracias por tu pregunta. La verdad que hay un error en esta definición y no se lee correctamente. La definición correcta es:

\delta es una **función parcial de transición** tal que:
(*) para todo p \in Q y A \in \Gamma, si \delta(p, \epsilon, A) esta definido, **entonces** para todo a \in \Sigma se cumple que \delta(p, a, A) no esta definido.

Aquí quiero mencionar dos errores. El primero está en el "**si y solo si**", ya que perfectamente el autómata puede no tener definido ninguna transición para p y A. Lo segundo es que en clases dije que la definición anterior se podía modificar con una función total. Esto es totalmente incorrecto, ya que si uno exige que la función sea total, entonces es imposible satisfacer la propiedad (*) de más arriba. Aquí es necesario que sea una función parcial para que todo tenga sentido. 

Gracias de nuevo por la pregunta y perdonen por el error durante la clase de ayer. 

Saludos!

**Comment by fgbruna** [comment]
Gracias!,
Con esto me surge una duda respecto a complementar un DPDA.Si no podemos "completar" la función de transición, sigue teniendo sentido la construcción del autómata complemento que usábamos en DFA, teniendo en cuenta que ahora habrá palabras que rechazará pero no quedaran en ningún estado(lo cual solucionabamos anteriormente usando sumideros) sino que su ejecución simplemente morirá?

**Comment by crivero1** [comment]
Hola Franco,

Si, tienes toda la razón. De hecho, ayer me di cuenta que mi explicación sobre complementar autómatas apiladores estaba totalmente errada. Siempre es posible complementar autómatas apiladores deterministas, pero NO solo cambiando estados finales por no finales. Los autómatas apiladores deterministas pueden rechazar una palabra no solo por llegar a un estado no final, si no que también porque (1) no tienen una siguiente transición (como mencionas), o (2) quedan pegado en un loop infinito con transiciones en epsilon. Por lo tanto, para complementar es necesario hacer algo más que cambiar estado finales por no finales. 

Mi plan es revisarlo nuevamente el Lunes para arreglar mi error y dejar esto bien claro, pero no esperaba que se dieran cuenta antes del Lunes. De todas maneras, te felicito por darte cuenta y preguntar en el foro. Gracias!

Saludos!
