### ISSUE TITLE
[Tarea 6] Pregunta 1.2

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#45]
Me pareció que hoy en clase se menciono una estructura similar a la de la tarea (y se menciono como tal) hablando de palindromos, es decir cosas del estilo u#v, donde v es u invertido. 

Es posible que hay un error en el enunciado? (nos piden hacer un autómata apilador que acepta palabras que no se pueden escribir como u#u) Quizas malinterprete lo que se dijo en clase, desde ya gracias.

**Comment by crivero1** [comment]
Hola Rudyard,

Lo que discutimos en clases es reconocer el lenguaje "u#u^rev" con un autómata apilador determinista. Lo único que mencioné es que se "parecía" a la tarea, solo en que la tarea el lenguaje son todas las palabras que NO son de la forma "u#u". Era solo mencionar que eran parecidos. 

Ahora bien, no hay ningún error en el enunciado y el lenguaje solicitado se puede decidir con un autómata apilador. Como hint, te recomiendo utilizar no-determinismo para adivinar que anda mal en la palabra que no tiene la forma "u#u". Para esto, el uso del stack es bien importante para verificar que lo que adivinaste con el no-determinismo es correcto.

Suerte!
