### ISSUE TITLE
[Tarea 6] Justificación de los autómatas 

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [PUC-IIC2223/syllabus2018#46]
Hola! Prefiero preguntar esto por si acaso, pero:

1. En la pregunta 1 se pide que expliquemos la respuesta. Imagino que el criterio es que veamos que sea correcto y completo, ¿verdad?

2. En la pregunta 2 no se explicita nada, pero asumo que también debemos mostrar que funciona lo que construimos, ¿verdad?

Muchas gracias
Saludos!

**Comment by crivero1** [comment]
Hola Alfonso,

Para la pregunta 1, si, lo que se pide es una explicación clara. No pedimos la demostración formal para no hacer la pregunta tan larga. De todas maneras, les recomiendo que hagan la demostración ustedes, es un buen ejercicio.

Para la pregunta 2, no se explicita pero en este caso si, deben demostrar que su construcción cumple con lo pedido, o sea es correcta y completa.

En general, cuando les pido que hagan una expresión regular, una gramática, etc, para un problema en particular (como la pregunta 1), tratamos de no pedirle la demostración formal ya que en casi todos los casos, de la misma definición se deduce la demostración. En cambio, para construcciones formales (como la pregunta 2) es necesario demostrar porque la construcción es correcta y completa.

Suerte!
