### ISSUE TITLE
[Duda de materia] Γ finito

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [PUC-IIC2223/syllabus2018#47]
Hola! Me entró la duda si un PDA tiene un Γ tal que es finito o si puede ser infinito, creo que nunca se restringe el tamaño de éste.

Gracias!
Saludos

**Comment by crivero1** [comment]
Hola Alfonso,

Si, el alfabeto \Gamma es siempre finito. Al parecer no lo menciono directamente en las slides, pero siempre que hablamos de un "alfabeto" este es un conjunto finito. 

Suerte!
