### ISSUE TITLE
[Duda de materia clase 15] Demostración de variables alcanzables y generadoras

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [PUC-IIC2223/syllabus2018#48]
Hola! Escribo porque hay una duda que tengo, es más bien conceptual, pero pienso que facilitaría las demostraciones. 
Cuando se define la clausura transitiva para definir derivaciones (Diapositiva 20 de clase 14), el paso general es que α⋆⇒β si α⋆⇒γ y γ ⇒β, pero ¿se podría definir alternativamente como α⇒γ' y γ'*⇒β? Pienso que facilitaría el demostrar que se cumple cierta condición cuando una variable es generadora  (Diapositiva 10 de clase 15) y alcanzable (Diapositiva 14 de clase 15). Pregunto también porque puede que no sea verdad que pasa eso, aunque intuitivamente pareciera que sí, quizá hay algún detalle que no se ve a simple vista.

Muchas gracias!
Saludos

**Comment by crivero1** [comment]
Hola Alfonso,

Perdona no haber respondido antes. 

Si se puede definir de forma alternativa como \alpha => \gamma' y \gamma' =>* \beta. Quizás esta otra definición queda todo más fácil de demostrar y entender. No me había dado cuenta.

Saludos!
