### ISSUE TITLE
Demostración correctitud  algoritmo CKY

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#49]
Estaba haciendo esta demostración, y en particular en el caso base debo demostrar lo siguiente:
![image](https://user-images.githubusercontent.com/26395700/48379792-1bd13f80-e6b4-11e8-92d3-ea5f30cf797d.png)
Pero mi duda es,
De derecha a izquierda no necesariamente se cumple, a menos que la gramática esté en forma normal o bien no tenga prods en vacio ni unitarias cierto?
Si es así, podría asumir que esta se encuentra en CNF o simplemente considero el caso base sin la clausura transitiva?
Gracias de antemano!

**Comment by crivero1** [comment]
Hola Franco,

Supongo que estas haciendo la demostración del algoritmo CKY. Si es así, en la presentación del algoritmo supusimos que la gramática estaba en forma normal de Chomsky y, por lo tanto, no tenía producciones unitarias ni en vacío. 

Suerte!
