### ISSUE TITLE
Descomposición de autómatas

### ISSUE THREAD

**Issue by benjavides** [PUC-IIC2223/syllabus2018#5]
Es siempre posible separar un autómata A en 2 autómatas A<sub>1</sub> y A<sub>2</sub> de modo que los estados finales de A<sub>1</sub> están conectados al estado inicial de A<sub>2</sub> ?
![image](https://user-images.githubusercontent.com/7333792/44820995-bfd53f80-abc9-11e8-8907-c5fdbd481a0c.png)

**Comment by crivero1** [comment]
Hola Benjamín, 

Habría que formalizar mejor tu pregunta. Si te refieres a separar el grupo de estados de A en dos grupos A1 y A2 que cumplan la propiedad que mencionas (sin agregar estados ni transiciones nuevas), entonces la respuesta es no. Piensa en un ciclo de n estados 0, 1, ..., n-1 donde cada uno pasa al siguiente estado al leer "a", o sea, (i, a, (i+1) \mod n), y el estado inicial y final es el 0. Este autómata verifica que el largo de la palabra sea múltiplo de "n". Ahora, como es un ciclo, no tienes como separarlo. 

Suerte!
