### ISSUE TITLE
[Lab 3] Fecha Entrega

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#50]
En el enunciado salen 2 fechas de entrega, al principio dice 30 de noviembre y al final dice 23 de noviembre. Cual es la fecha de entrega?

**Comment by fdoflorenzano** [comment]
Hola, la primera fecha es la correcta. 2 semanas después de su publicación. La segunda es un error (la fecha original programada para el laboratorio).
Saludos.
