### ISSUE TITLE
[Lab 3]  Error Instalación ANTLR

### ISSUE THREAD

**Issue by rudyjb24** [PUC-IIC2223/syllabus2018#51]
Estoy siguiendo el tutorial de instalacion de los links que nos proporcionaron en el enunciado. Cuando corro el comando: curl -O https://www.antlr.org/download/antlr-4.7.1-complete.jar
me aparece el error: curl: (23) Failed writing body (0 != 2401)

He tratado de resolver el error y buscar otros métodos de instalación, pero no lo he logrado

**Comment by fdoflorenzano** [comment]
Estimado, desconozco porque no te funciona el comando sin más detalles, pero ¿intentaste descargar directamente el `.jar` usando ese mismo enlace? Luego debes ubicar el archivo en algún lugar conveniente de tu máquina, como dice [este enlance](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md).
Saludos.

**Comment by ManuelOchagavia** [comment]
Hola, yo también he intentado seguir los tutoriales de instalación pero me sale error tras error. Ya he buscado bastante en internet y no he dado con nada que pueda ayudarme. Saben de algún tutorial que no se salte pasos o tal vez que no dé algunas cosas por sabidas?
Gracias.

**Comment by rudyjb24** [comment]
Me funciono descargar el .jar a mano.

**Comment by ifieldhouse** [comment]
Yo usé el [tutorial en github](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md): principalmente las secciones **Installation: UNIX** y luego **Testing Installation**.

Notar que es necesario tener Java Development Kit (`sudo apt install default-jdk`) y Curl (`sudo apt install curl`) instalados, y si algo no funciona probablemente `sudo` logre hacer el trabajo (especialmente con Curl). Luego, para poder usarlo con Python hay que ejecutar `sudo pip3 install antlr4-python3-runtime`.

Tal vez haya que configurar más cosas previamente, pero para eso sería necesario saber los errores particulares.

**Comment by ifieldhouse** [comment]
Otra cosa que me di cuenta es que
```
alias antlr4='java -Xmx500M -cp "/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH" org.antlr.v4.Tool'
alias grun='java -Xmx500M -cp "/usr/local/lib/antlr-4.7.1-complete.jar:$CLASSPATH" org.antlr.v4.gui.TestRig'
```
deben escribirse en el archivo de start-up de tu _shell_ (e.g. `~/.bashrc` o `~/.zshrc`), sino el alias será temporal, y no podrás ejecutar `antlr4` luego de cerrar la consola.

**Comment by crivero1** [comment]
Gracias Ian por tus comentarios. 

Saludos!
