### ISSUE TITLE
Es necesario el uso de ANTLR, o se puede generar el resultado solo con un algoritmo propio?

### ISSUE THREAD

**Issue by marianoll** [PUC-IIC2223/syllabus2018#54]
Digo esto principalmente, por que el trabajo de Parsing no es la dificultad del problema. Y es posible resolver el problema con una clara inspiracion a un algoritmo mostrado en clases de Estructura de Datos.

**Comment by crivero1** [comment]
Hola Mariano,

Es necesario hacerlo con ANTLR. El objetivo del laboratorio es que tengan la experiencia de usar un generador de parsing autómatico. Colocamos una gramática sencilla y simplificada, solo para disminuir tareas repetitivas. Podríamos haber colocado una gramática con todas las extensiones de RegEx, pero al final eso solo iba a agregar trabajo repetitivo. 

Claramente como la gramática es sencilla, este trabajo de parsing quizás lo podrían haber hecho a "mano". Ahora insisto en que la finalidad no es el resultado (un parsing para expresiones regulares) si no la experiencia práctica de usar un generador de parsers. 

Saludos!

**Comment by marianoll** [comment]
Ya perfecto, lo decia principalmente por que el sistema de regex es lineal (Aunque no lo paresca). Y una modificacion a algun algoritmo como Shunting-Yard para aritmetica en funcion de stacks seria una aproximacion bastante eficiente (tiempo en O(n)). Ademas pregunte por que ya lo tenia hecho.
