### ISSUE TITLE
Resultado de ANTLR

### ISSUE THREAD

**Issue by Jaluco** [PUC-IIC2223/syllabus2018#55]
Hola, leyendo el enunciado no me queda muy claro lo que debería retornar ANTLR, dada la expresion regular nos entrega algo que debemos transformar a la notación de autómatas que nos dieron?

**Comment by ifieldhouse** [comment]
Según entiendo, con antlr defines una gramática, y este genera un árbol de derivaciones según el Regex que le des. Entonces, a partir del árbol se debe hacer el autómata.

**Comment by crivero1** [comment]
Exactamente. Deben construir un autómata equivalente a la expresión regular que reciben como input. Para esto deben generar el arbol de parsing de la gramática sobre el input, y apartir de ese árbol construir inductivamente el autómata. El formato de output del autómata es el mismo que hemos usado durante todos los laboratorios. 

¿Queda claro?

Suerte!
