### ISSUE TITLE
Can't load Chat as a lexer or parser

### ISSUE THREAD

**Issue by llloyola** [PUC-IIC2223/syllabus2018#56]
Hola! He estado intentando seguir uno de los tutoriales del enunciado, pero no hay caso :( Sigo pegado en el error "Can't load Chat as a lexer or parser" al intentar usar grun
Alguna idea de qué podría hacer al respecto?

**Comment by fgbruna** [comment]
Eso pasa porque a grun le entregas solo la gramática, debes entregarle una regla desde donde quieres que construya el árbol de parsing, por ejemplo si tienes una variable inicial debes escribir:
```bash
grun .... Chat var_inicial ...
```

**Comment by llloyola** [comment]
De hecho, le estoy pasando ```grun Chat chat -tokens```

**Comment by fgbruna** [comment]
Y compilaste los archivos?, se me ocurre que solo corriste `antlr` y no compilaste los archivos .java que esto te generó.
