### ISSUE TITLE
Duda P2 Ayudantía 9

### ISSUE THREAD

**Issue by fgbruna** [PUC-IIC2223/syllabus2018#58]
En la pregunta 2 de la ayudantía de repaso, específicamente en la sección donde queremos demostrar que L(A) es subconjunto de ramas(G) no me queda claro por qué es necesario lo que viene después de "Ahora sirve el argumento de variables generadoras...".
Es por que queremos demostrar que efectivamente existe un árbol del cual w es rama y para esto demostramos que produce una palabra de la gramática? o es por otra razón?
Gracias de antemano!

**Comment by fdoflorenzano** [comment]
Hola Franco, es por esa razón el argumento. ramas(G) se define como la unión de todas las ramas de árboles válidos, luego, si quiero mostrar que w está en ramas(G), debo encontrar el árbol al cual pertenece, o argumentar por que debe existir tal árbol. Si no hubiésemos eliminado variables inútiles, no hubiésemos podido demostrarlo, ya que si bien podemos formar una rama, no necesariamente pertenece a un árbol válido (como el ejemplo con la variable B). Pero, como toda variable es generadora en G', sabemos que podemos completar un árbol de derivación válido usando la rama.

¿Se entiende?

Saludos.

**Comment by fgbruna** [comment]
Clarísimo, muchas gracias!
