### ISSUE TITLE
[Tarea 2] - Nivel de detalle pregunta 1.1

### ISSUE THREAD

**Issue by AlfonsoIgnacioV** [PUC-IIC2223/syllabus2018#8]
Hola! Escribo para preguntar qué nivel de detalle se espera en la explicación de la construcción del autómata, ya que tengo una manera de hacerlo, pero explicar todo lo que hice puede resultar un poco extenso. En particular, si usamos algo visto en clases, ¿Basta con decir que lo vimos en clases o se espera que también demostremos que lo que hicimos funciona? 

Muchas gracias
Saludos

**Comment by crivero1** [comment]
Hola Alfonso,

Esperamos que la construcción este formalizada matemáticamente como las construcciones que hemos visto en clases. Un buen ejemplo son las construcciones que hicimos para la intersección, la determinización, o las construcciones en el Teorema de Kleene. Ahora, siempre es bueno que agregues una explicación de la construcción. Para esta explicación, entre más detalles, mejor. 

Recuerda que al final también debes demostrar que tu construcción es correcta, osea, que L(A) = L(A') siendo A' el nuevo autómata que construiste a partir de A.

Suerte!

**Comment by fgbruna** [comment]
Profesor a mi me queda una duda ya que en clases ya vimos la construcción inductiva de los autómatas para las expresiones regulares más comunes, por lo que no me queda claro que es lo que tendríamos que construir nosotros más que la eliminación de las epsilon transiciones del autómata resultante del algoritmo.

**Comment by crivero1** [comment]
Perdonen la confusión. Mi respuesta estaba pensada para la pregunta 2. Para la pregunta 1, basta que hagan la construcción explicando que están haciendo en cada caso. Si usan algo visto en clases, basta que lo mencionen. 

Suerte!
