### ISSUE TITLE
[Tarea 2] NFA

### ISSUE THREAD

**Issue by fgvenegas** [PUC-IIC2223/syllabus2018#9]
Para la 1.1, ¿Podemos hacer una automata no determinista parcial y no uno total? para evitar hacer muchas transiciones que irían a un sumidero, por claridad del autómata.

Gracias!

**Comment by fdoflorenzano** [comment]
Hola Freddie, 
Recuerda que la definición de NFA utiliza una **relación** de transición, y **no** una **función**. Por lo tanto, no hay restricciones sobre si están definidas las transiciones para todo el alfabeto, en todos los estados. Es decir, puede ser "parcial", ya que todo NFA puede serlo.
Saludos.
